#!/usr/bin/env python3
"""Generate a sparse LP in free-format MPS for backend timing comparisons.

Synthetic and seeded -- no confidential data, reproducible from the seed alone
(sor/docs/master_spec.md: industrial generators must record their seed).

Shape:  min c'x  s.t.  lo_i <= sum_j A_ij x_j <= hi_i,  0 <= x_j <= u_j
with `nnz_per_row` entries per row, so the pattern is genuinely sparse rather
than banded.
"""
import argparse
import random


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=10000)
    ap.add_argument("--cols", type=int, default=10000)
    ap.add_argument("--nnz-per-row", type=int, default=8)
    ap.add_argument("--seed", type=int, default=20260828)
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    rng = random.Random(args.seed)
    m, n = args.rows, args.cols

    # Column-major accumulation: MPS COLUMNS requires all entries of a column
    # to be contiguous.
    cols: list[list[tuple[int, float]]] = [[] for _ in range(n)]
    for r in range(m):
        seen = set()
        # One guaranteed entry so no row is empty.
        j0 = r % n
        cols[j0].append((r, 1.0 + 0.1 * rng.random()))
        seen.add(j0)
        for _ in range(args.nnz_per_row - 1):
            j = rng.randrange(n)
            if j in seen:
                continue
            seen.add(j)
            cols[j].append((r, 2.0 * rng.random() - 1.0))

    obj = [round(-1.0 - rng.random(), 6) for _ in range(n)]
    ub = [round(1.0 + 9.0 * rng.random(), 6) for _ in range(n)]
    rhs = [round(5.0 + 20.0 * rng.random(), 6) for _ in range(m)]

    nnz = sum(len(c) for c in cols)
    with open(args.out, "w") as f:
        f.write(f"* generated by gen_sparse_lp.py seed={args.seed} "
                f"rows={m} cols={n} nnz={nnz}\n")
        f.write("NAME          SPARSELP\n")
        f.write("ROWS\n N  COST\n")
        for r in range(m):
            f.write(f" L  R{r}\n")
        f.write("COLUMNS\n")
        for j in range(n):
            f.write(f"    X{j}  COST  {obj[j]!r}\n")
            for (r, v) in cols[j]:
                f.write(f"    X{j}  R{r}  {round(v, 6)!r}\n")
        f.write("RHS\n")
        for r in range(m):
            f.write(f"    RHS  R{r}  {rhs[r]!r}\n")
        f.write("BOUNDS\n")
        for j in range(n):
            f.write(f" UP BND  X{j}  {ub[j]!r}\n")
        f.write("ENDATA\n")

    print(f"wrote {args.out}: {m} rows x {n} cols, {nnz} nnz")


if __name__ == "__main__":
    main()
